shell/bat script

diff --git a/packaging/src/main/distribution/bin/neo4j b/packaging/src/main/distribution/bin/neo4j
--- a/packaging/src/main/distribution/bin/neo4j
+++ b/packaging/src/main/distribution/bin/neo4j
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# Copyright (c) 2002-2019 "Pandadb,"
-# Pandadb Sweden AB [http://pandadb.com]
+# Copyright (c) 2002-2019 "Neo4j,"
+# Neo4j Sweden AB [http://neo4j.com]
 #
-# This file is part of Pandadb.
+# This file is part of Neo4j.
 #
-# Pandadb is free software: you can redistribute it and/or modify
+# Neo4j is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
@@ -21,9 +21,9 @@
 # Callers may provide the following environment variables to customize this script:
 #  * JAVA_HOME
 #  * JAVA_CMD
-#  * PANDADB_HOME
-#  * PANDADB_CONF
-#  * PANDADB_START_WAIT
+#  * NEO4J_HOME
+#  * NEO4J_CONF
+#  * NEO4J_START_WAIT
 
 #############################################################
 #      File content is generated based on .m4 template      #
@@ -34,16 +34,16 @@ set -o errexit -o nounset -o pipefail
 
 declare -r PROGRAM="$(basename "$0")"
 
-# Sets up the standard environment for running Pandadb shell scripts.
+# Sets up the standard environment for running Neo4j shell scripts.
 #
 # Provides these environment variables:
-#   PANDADB_HOME
-#   PANDADB_CONF
-#   PANDADB_DATA
-#   PANDADB_LIB
-#   PANDADB_LOGS
-#   PANDADB_PIDFILE
-#   PANDADB_PLUGINS
+#   NEO4J_HOME
+#   NEO4J_CONF
+#   NEO4J_DATA
+#   NEO4J_LIB
+#   NEO4J_LOGS
+#   NEO4J_PIDFILE
+#   NEO4J_PLUGINS
 #   one per config setting, with dots converted to underscores
 #
 setup_environment() {
@@ -60,14 +60,15 @@ setup_heap() {
 }
 
 build_classpath() {
-  CLASSPATH="${PANDADB_LIB}/*"
+
+  CLASSPATH="${NEO4J_LIB}/*"
 
   # augment with tools.jar, will need JDK
   if [ "${JAVA_HOME:-}" ]; then
     JAVA_TOOLS="${JAVA_HOME}/lib/tools.jar"
-	# if [[ -e $JAVA_TOOLS ]]; then
-      # CLASSPATH="${CLASSPATH}:${JAVA_TOOLS}"
-    # fi
+#    if [[ -e $JAVA_TOOLS ]]; then
+#      CLASSPATH="${CLASSPATH}:${JAVA_TOOLS}"
+#    fi
   fi
 }
 
@@ -89,7 +90,7 @@ setup_memory_opts() {
       mem="${mem}m"
       cat >&2 <<EOF
 WARNING: dbms.memory.heap.initial_size will require a unit suffix in a
-         future version of Pandadb. Please add a unit suffix to your
+         future version of Neo4j. Please add a unit suffix to your
          configuration. Example:
 
          dbms.memory.heap.initial_size=512m
@@ -105,7 +106,7 @@ EOF
       mem="${mem}m"
       cat >&2 <<EOF
 WARNING: dbms.memory.heap.max_size will require a unit suffix in a
-         future version of Pandadb. Please add a unit suffix to your
+         future version of Neo4j. Please add a unit suffix to your
          configuration. Example:
 
          dbms.memory.heap.max_size=512m
@@ -125,7 +126,7 @@ check_java() {
   JAVA_VERSION=$("${version_command[@]}" 2>&1 | awk -F '"' '/version/ {print $2}')
   if [[ $JAVA_VERSION = "1."* ]]; then
     if [[ "${JAVA_VERSION}" < "1.8" ]]; then
-      echo "ERROR! Pandadb cannot be started using java version ${JAVA_VERSION}. "
+      echo "ERROR! Neo4j cannot be started using java version ${JAVA_VERSION}. "
       _show_java_help
       exit 1
     fi
@@ -146,14 +147,14 @@ unsupported_runtime_warning() {
     _show_java_help
 }
 
-# Resolve a path relative to $PANDADB_HOME.  Don't resolve if
+# Resolve a path relative to $NEO4J_HOME.  Don't resolve if
 # the path is absolute.
 resolve_path() {
     orig_filename=$1
     if [[ ${orig_filename} == /* ]]; then
         filename="${orig_filename}"
     else
-        filename="${PANDADB_HOME}/${orig_filename}"
+        filename="${NEO4J_HOME}/${orig_filename}"
     fi
     echo "${filename}"
 }
@@ -166,7 +167,7 @@ call_main_class() {
   class_name=$1
   shift
 
-  export PANDADB_HOME PANDADB_CONF
+  export NEO4J_HOME NEO4J_CONF
 
   exec "${JAVA_CMD}" ${JAVA_OPTS:-} ${JAVA_MEMORY_OPTS_XMS-} ${JAVA_MEMORY_OPTS_XMX-} \
     -classpath "${CLASSPATH}" \
@@ -213,16 +214,15 @@ _find_java_home() {
 }
 
 _show_java_help() {
-  echo "* Please use Oracle(R) Java(TM) 8, OpenJDK(TM) or IBM J9 to run Pandadb."
-  echo "* Please see https://pandadb.com/docs/ for Pandadb installation instructions."
+  echo "* Please use Oracle(R) Java(TM) 8, OpenJDK(TM) or IBM J9 to run Neo4j."
+  echo "* Please see https://neo4j.com/docs/ for Neo4j installation instructions."
 }
 
 _setup_calculated_paths() {
-  if [[ -z "${PANDADB_HOME:-}" ]]; then
-    PANDADB_HOME="$(cd "$(dirname "$0")"/.. && pwd)"
+  if [[ -z "${NEO4J_HOME:-}" ]]; then
+    NEO4J_HOME="$(cd "$(dirname "$0")"/.. && pwd)"
   fi
-  : "${PANDADB_CONF:="${PANDADB_HOME}/conf"}"
-  readonly PANDADB_HOME PANDADB_CONF
+  : "${NEO4J_CONF:="../conf"}"
 }
 
 _read_config() {
@@ -250,8 +250,15 @@ _read_config() {
     fi
   }
 
-  for file in "${PANDADB_CONF}"; do
-    path="${PANDADB_CONF}/neo4j.conf"
+  if [[ -f "${NEO4J_CONF}/neo4j-wrapper.conf" ]]; then
+    cat >&2 <<EOF
+WARNING: neo4j-wrapper.conf is deprecated and support for it will be removed in a future
+         version of Neo4j; please move all your settings to neo4j.conf
+EOF
+  fi
+
+  for file in "neo4j.conf"; do
+    path="$NEO4J_CONF/neo4j.conf"
     if [ -e "${path}" ]; then
       while read line; do
         parse_line "${line}"
@@ -261,33 +268,31 @@ _read_config() {
 }
 
 _setup_configurable_paths() {
-  PANDADB_DATA=$(resolve_path "${dbms_directories_data:-data}")
-  PANDADB_LIB=$(resolve_path "${dbms_directories_lib:-lib}")
-  PANDADB_LOGS=$(resolve_path "${dbms_directories_logs:-logs}")
-  PANDADB_PLUGINS=$(resolve_path "${dbms_directories_plugins:-plugins}")
-  PANDADB_RUN=$(resolve_path "${dbms_directories_run:-run}")
-  PANDADB_CERTS=$(resolve_path "${dbms_directories_certificates:-certificates}")
+  NEO4J_DATA=$(resolve_path "${dbms_directories_data:-data}")
+  NEO4J_LIB=$(resolve_path "${dbms_directories_lib:-lib}")
+  NEO4J_LOGS=$(resolve_path "${dbms_directories_logs:-logs}")
+  NEO4J_PLUGINS=$(resolve_path "${dbms_directories_plugins:-plugins}")
+  NEO4J_RUN=$(resolve_path "${dbms_directories_run:-run}")
+  NEO4J_CERTS=$(resolve_path "${dbms_directories_certificates:-certificates}")
 
   if [ -z "${dbms_directories_import:-}" ]; then
-    PANDADB_IMPORT="NOT SET"
+    NEO4J_IMPORT="NOT SET"
   else
-    PANDADB_IMPORT=$(resolve_path "${dbms_directories_import:-}")
+    NEO4J_IMPORT=$(resolve_path "${dbms_directories_import:-}")
   fi
-
-  readonly PANDADB_DATA PANDADB_LIB PANDADB_LOGS PANDADB_PLUGINS PANDADB_RUN PANDADB_IMPORT PANDADB_CERTS
 }
 
 print_configurable_paths() {
   cat <<EOF
 Directories in use:
-  home:         ${PANDADB_HOME}
-  config:       ${PANDADB_CONF}
-  logs:         ${PANDADB_LOGS}
-  plugins:      ${PANDADB_PLUGINS}
-  import:       ${PANDADB_IMPORT}
-  data:         ${PANDADB_DATA}
-  certificates: ${PANDADB_CERTS}
-  run:          ${PANDADB_RUN}
+  home:         ${NEO4J_HOME}
+  config:       ${NEO4J_CONF}
+  logs:         ${NEO4J_LOGS}
+  plugins:      ${NEO4J_PLUGINS}
+  import:       ${NEO4J_IMPORT}
+  data:         ${NEO4J_DATA}
+  certificates: ${NEO4J_CERTS}
+  run:          ${NEO4J_RUN}
 EOF
 }
 
@@ -295,40 +300,41 @@ print_active_database() {
   echo "Active database: ${dbms_active_database:-graph.db}"
 }
 
+
 setup_arbiter_options() {
-    SHUTDOWN_TIMEOUT="${PANDADB_SHUTDOWN_TIMEOUT:-120}"
+    SHUTDOWN_TIMEOUT="${NEO4J_SHUTDOWN_TIMEOUT:-120}"
     MIN_ALLOWED_OPEN_FILES=40000
     MAIN_CLASS="org.neo4j.server.CommunityEntryPoint"
 
     print_start_message() {
       # Global default
-      PANDADB_DEFAULT_ADDRESS="${dbms_connectors_default_listen_address:-localhost}"
+      NEO4J_DEFAULT_ADDRESS="${dbms_connectors_default_listen_address:-localhost}"
 
       if [[ "${dbms_connector_http_enabled:-true}" == "false" ]]; then
         # Only HTTPS connector enabled
         # First read deprecated 'address' setting
-        PANDADB_SERVER_ADDRESS="${dbms_connector_https_address:-:7473}"
+        NEO4J_SERVER_ADDRESS="${dbms_connector_https_address:-:7473}"
         # Overridden by newer 'listen_address' if specified
-        PANDADB_SERVER_ADDRESS="${dbms_connector_https_listen_address:-${PANDADB_SERVER_ADDRESS}}"
+        NEO4J_SERVER_ADDRESS="${dbms_connector_https_listen_address:-${NEO4J_SERVER_ADDRESS}}"
         # If it's only a port we need to add the address (it starts with a colon in that case)
-        case ${PANDADB_SERVER_ADDRESS} in
+        case ${NEO4J_SERVER_ADDRESS} in
           :*)
-            PANDADB_SERVER_ADDRESS="${PANDADB_DEFAULT_ADDRESS}${PANDADB_SERVER_ADDRESS}";;
+            NEO4J_SERVER_ADDRESS="${NEO4J_DEFAULT_ADDRESS}${NEO4J_SERVER_ADDRESS}";;
         esac
         # Add protocol
-        PANDADB_SERVER_ADDRESS="https://${PANDADB_SERVER_ADDRESS}"
+        NEO4J_SERVER_ADDRESS="https://${NEO4J_SERVER_ADDRESS}"
       else
         # HTTP connector enabled - same as https but different settings
-        PANDADB_SERVER_ADDRESS="${dbms_connector_http_address:-:7474}"
-        PANDADB_SERVER_ADDRESS="${dbms_connector_http_listen_address:-${PANDADB_SERVER_ADDRESS}}"
-        case ${PANDADB_SERVER_ADDRESS} in
+        NEO4J_SERVER_ADDRESS="${dbms_connector_http_address:-:7474}"
+        NEO4J_SERVER_ADDRESS="${dbms_connector_http_listen_address:-${NEO4J_SERVER_ADDRESS}}"
+        case ${NEO4J_SERVER_ADDRESS} in
           :*)
-            PANDADB_SERVER_ADDRESS="${PANDADB_DEFAULT_ADDRESS}${PANDADB_SERVER_ADDRESS}";;
+            NEO4J_SERVER_ADDRESS="${NEO4J_DEFAULT_ADDRESS}${NEO4J_SERVER_ADDRESS}";;
         esac
-        PANDADB_SERVER_ADDRESS="http://${PANDADB_SERVER_ADDRESS}"
+        NEO4J_SERVER_ADDRESS="http://${NEO4J_SERVER_ADDRESS}"
       fi
 
-      echo "Started pandadb (pid ${PANDADB_PID}). It is available at ${PANDADB_SERVER_ADDRESS}"
+      echo "Started neo4j (pid ${NEO4J_PID}). It is available at ${NEO4J_SERVER_ADDRESS}"
 
       if [[ "$(echo "${dbms_mode:-}" | tr [:lower:] [:upper:])" == "HA" ]]; then
         echo "This HA instance will be operational once it has joined the cluster."
@@ -339,9 +345,9 @@ setup_arbiter_options() {
 }
 
 check_status() {
-  if [ -e "${PANDADB_PIDFILE}" ] ; then
-    PANDADB_PID=$(cat "${PANDADB_PIDFILE}")
-    kill -0 "${PANDADB_PID}" 2>/dev/null || unset PANDADB_PID
+  if [ -e "${NEO4J_PIDFILE}" ] ; then
+    NEO4J_PID=$(cat "${NEO4J_PIDFILE}")
+    kill -0 "${NEO4J_PID}" 2>/dev/null || unset NEO4J_PID
   fi
 }
 
@@ -351,7 +357,7 @@ check_limits() {
     ALLOWED_OPEN_FILES="$(ulimit -n)"
 
     if [ "${ALLOWED_OPEN_FILES}" -lt "${MIN_ALLOWED_OPEN_FILES}" ]; then
-      echo "WARNING: Max ${ALLOWED_OPEN_FILES} open files allowed, minimum of ${MIN_ALLOWED_OPEN_FILES} recommended. See the Pandadb manual."
+      echo "WARNING: Max ${ALLOWED_OPEN_FILES} open files allowed, minimum of ${MIN_ALLOWED_OPEN_FILES} recommended. See the Neo4j manual."
     fi
   fi
 }
@@ -362,7 +368,7 @@ setup_java_opts() {
   if [[ "${dbms_logs_gc_enabled:-}" = "true" ]]; then
     if [[ "${JAVA_VERSION}" = "1.8"* ]]; then
       # JAVA 8 GC logging setup
-      JAVA_OPTS+=("-Xloggc:${PANDADB_LOGS}/gc.log" \
+      JAVA_OPTS+=("-Xloggc:${NEO4J_LOGS}/gc.log" \
                   "-XX:+UseGCLogFileRotation" \
                   "-XX:NumberOfGCLogFiles=${dbms_logs_gc_rotation_keep_number:-5}" \
                   "-XX:GCLogFileSize=${dbms_logs_gc_rotation_size:-20m}")
@@ -380,7 +386,7 @@ setup_java_opts() {
       else
         gc_options="-Xlog:gc*,safepoint,age*=trace"
       fi
-      gc_options+=":file=${PANDADB_LOGS}/gc.log::filecount=${dbms_logs_gc_rotation_keep_number:-5},filesize=${dbms_logs_gc_rotation_size:-20m}"
+      gc_options+=":file=${NEO4J_LOGS}/gc.log::filecount=${dbms_logs_gc_rotation_keep_number:-5},filesize=${dbms_logs_gc_rotation_size:-20m}"
       JAVA_OPTS+=(${gc_options})
     fi
   fi
@@ -392,17 +398,17 @@ setup_java_opts() {
 
 assemble_command_line() {
   retval=("${JAVA_CMD}" "-cp" "${CLASSPATH}" "${JAVA_OPTS[@]}" "-Dfile.encoding=UTF-8" "${MAIN_CLASS}" \
-   "--home-dir=${PANDADB_HOME}" "--config-dir=${PANDADB_CONF}")
+          "-server" "--home-dir=$NEO4J_HOME" "--config-dir=$NEO4J_CONF")
 }
 
 do_console() {
   check_status
-  if [[ "${PANDADB_PID:-}" ]] ; then
-    echo "Pandadb is already running (pid ${PANDADB_PID})."
+  if [[ "${NEO4J_PID:-}" ]] ; then
+    echo "Neo4j is already running (pid ${NEO4J_PID})."
     exit 1
   fi
 
-  echo "Starting Pandadb."
+  echo "Starting Neo4j."
 
   check_limits
   build_classpath
@@ -414,40 +420,37 @@ do_console() {
 
 do_start() {
   check_status
-  if [[ "${PANDADB_PID:-}" ]] ; then
-    echo "Pandadb is already running (pid ${PANDADB_PID})."
+  if [[ "${NEO4J_PID:-}" ]] ; then
+    echo "Neo4j is already running (pid ${NEO4J_PID})."
     exit 0
   fi
   # check dir for pidfile exists
-  if [[ ! -d $(dirname "${PANDADB_PIDFILE}") ]]; then
-    mkdir -p $(dirname "${PANDADB_PIDFILE}")
+  if [[ ! -d $(dirname "${NEO4J_PIDFILE}") ]]; then
+    mkdir -p $(dirname "${NEO4J_PIDFILE}")
   fi
 
-  echo "Starting Pandadb."
+  echo "Starting Neo4j."
 
   check_limits
   build_classpath
 
   assemble_command_line
   command_line=("${retval[@]}")
-  if [[ ! -d $(dirname "${CONSOLE_LOG}") ]]; then
-    mkdir -p $(dirname "${CONSOLE_LOG}")
-  fi
   nohup "${command_line[@]}" >>"${CONSOLE_LOG}" 2>&1 &
-  echo "$!" >"${PANDADB_PIDFILE}"
+  echo "$!" >"${NEO4J_PIDFILE}"
 
-  : "${PANDADB_START_WAIT:=5}"
-  end="$((SECONDS+PANDADB_START_WAIT))"
+  : "${NEO4J_START_WAIT:=5}"
+  end="$((SECONDS+NEO4J_START_WAIT))"
   while true; do
     check_status
 
-    if [[ "${PANDADB_PID:-}" ]]; then
+    if [[ "${NEO4J_PID:-}" ]]; then
       break
     fi
 
     if [[ "${SECONDS}" -ge "${end}" ]]; then
       echo "Unable to start. See ${CONSOLE_LOG} for details."
-      rm "${PANDADB_PIDFILE}"
+      rm "${NEO4J_PIDFILE}"
       return 1
     fi
 
@@ -456,62 +459,27 @@ do_start() {
 
   print_start_message
   echo "See ${CONSOLE_LOG} for current status."
-  wait $(cat "${PANDADB_PIDFILE}")
 }
 
 do_stop() {
-  
-	
-	if [ ! -f "$PANDADB_PIDFILE" ] || ! kill -0 "$(cat "$PANDADB_PIDFILE")"; then
-		echo "Pandadb is not running..."
+  if [ ! -f "$NEO4J_PIDFILE" ] || ! kill -0 "$(cat "$NEO4J_PIDFILE")"; then
+		echo "Neo4j is not running"
 	else
-		echo "stopping Pandadb..."
-		PID="$(cat "$PANDADB_PIDFILE")"
+		echo "Stopping Neo4j"
+		PID="$(cat "$NEO4J_PIDFILE")"
 		kill -9 $PID
-		rm "$PANDADB_PIDFILE"
-		echo "Pandadb stopped"
+		rm "$NEO4J_PIDFILE"
+		echo "Neo4j stopped"
 	fi
-	
-  # check_status
-	
-  # if [[ ! "${PANDADB_PID:-}" ]] ; then
-    # echo "Pandadb not running"
-    # [ -e "${PANDADB_PIDFILE}" ] && rm "${PANDADB_PIDFILE}"
-    # return 0
-  # else
-    # echo -n "Stopping Pandadb."
-    # end="$((SECONDS+SHUTDOWN_TIMEOUT))"
-    # while true; do
-      # check_status
-
-      # if [[ ! "${PANDADB_PID:-}" ]]; then
-        # echo " stopped"
-        # [ -e "${PANDADB_PIDFILE}" ] && rm "${PANDADB_PIDFILE}"
-        # return 0
-      # fi
-
-      # kill "${PANDADB_PID}" 2>/dev/null || true
-
-      # if [[ "${SECONDS}" -ge "${end}" ]]; then
-        # echo " failed to stop"
-        # echo "Pandadb (pid ${PANDADB_PID}) took more than ${SHUTDOWN_TIMEOUT} seconds to stop."
-        # echo "Please see ${CONSOLE_LOG} for details."
-        # return 1
-      # fi
-
-      # echo -n "."
-      # sleep 1
-    # done
-  # fi
 }
 
 do_status() {
   check_status
-  if [[ ! "${PANDADB_PID:-}" ]] ; then
-    echo "Pandadb is not running"
+  if [[ ! "${NEO4J_PID:-}" ]] ; then
+    echo "Neo4j is not running"
     exit 3
   else
-    echo "Pandadb is running at pid ${PANDADB_PID}"
+    echo "Neo4j is running at pid ${NEO4J_PID}"
   fi
 }
 
@@ -531,9 +499,18 @@ setup_java () {
 
 main() {
   setup_environment
-  CONSOLE_LOG="${PANDADB_LOGS}/pandadb.log"
-  PANDADB_PIDFILE="${PANDADB_RUN}/pandadb.pid"
-  readonly CONSOLE_LOG
+  NEO4J_HOME=$(dirname $(pwd))
+  NEO4J_CONF=$NEO4J_HOME/conf
+  NEO4J_LIB=$NEO4J_HOME/lib
+  NEO4J_LOGS=$NEO4J_HOME/logs
+  NEO4J_RUN=$NEO4J_HOME/run
+  NEO4J_DATA=$NEO4J_HOME/data
+  NEO4J_PLUGINS=$NEO4J_HOME/plugins
+  NEO4J_CERTS=$NEO4J_HOME/certificates
+  readonly NEO4J_HOME NEO4J_CONF NEO4J_LIB NEO4J_LOGS NEO4J_RUN NEO4J_DATA NEO4J_PLUGINS NEO4J_CERTS
+  CONSOLE_LOG="${NEO4J_LOGS}/neo4j.log"
+  NEO4J_PIDFILE="${NEO4J_RUN}/neo4j.pid"
+  readonly CONSOLE_LOG NEO4J_PIDFILE
 
   case "${1:-}" in
     console)
